name: Update Submodule

on:
  # schedule:
    # - cron: '0 0 * * 0'  # Runs weekily at midnight UTC / Minute/Hour/Day of Month/Month/Day of Week
  
  workflow_dispatch: # Allows manual trigger

  repository_dispatch: # Allows one repo to trigger a workflow in another repo
    types: [submodule-updated]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 
        with:
          submodules: true
          fetch-depth: 0

      # Fetches latest commit from the submodule's remote main branch and 
      # merges it into the submodule directory in the main repo
      - name: Update Submodule
        run: |
            git submodule update --remote --merge project/realtek_amebapro2_v0_example/scenario/ai_glass/src/common_basics

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://${GH_PAT}@github.com/sihjiaqi/ameba-rtos-pro2.git
          git add project/realtek_amebapro2_v0_example/scenario/ai_glass/src/common_basics
          git commit -m "Auto-update submodule: common_basics [$(date)]" || echo "No changes to commit"
          git push